disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - force_cast
  - identifier_name
  - ignores_empty_lines
  - large_tuple
  - line_length
  - todo
  - trailing_whitespace
  - type_body_length
